POST http://localhost:3000/user/singup
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "$_24^#dd"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "example2@gmail.com",
  "password": "$_24^#dd"
}
