POST http://localhost:3000/user/singup
Content-Type: application/json

{
  "email": "al@noreplay.com",
  "password": "#123456"
}


###


POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "nirob@noreplay.com",
  "password": "#123456"
}


###


GET http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgxOTU2OX0.qGtWsKkEDvq5qtV8BMD9qAlnRFjKMv3ffWO5_yRskNY


###


POST  http://localhost:3000/chat/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgxOTU2OX0.qGtWsKkEDvq5qtV8BMD9qAlnRFjKMv3ffWO5_yRskNY
Content-Type: application/json

{
  "id": "643e879914a641e4a41fcbea" 
}

###


GET  http://localhost:3000/chat/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgxOTU2OX0.qGtWsKkEDvq5qtV8BMD9qAlnRFjKMv3ffWO5_yRskNY
Content-Type: application/json


###


POST http://localhost:3000/chat/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgxOTU2OX0.qGtWsKkEDvq5qtV8BMD9qAlnRFjKMv3ffWO5_yRskNY
Content-Type: application/json

{
  "userArray": "[\"643e87ccc52268e4c0bb8e75\", \"643e8713da47d89ef0d09b6c\"]",
  "groupName": "private-chat-group"
}


###


POST http://localhost:3000/chat/group/rename
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgxOTU2OX0.qGtWsKkEDvq5qtV8BMD9qAlnRFjKMv3ffWO5_yRskNY
Content-Type: application/json

{
  "groupId": "643e88e1e07d67abe5c1bb47",
  "updatedGroupName": "private-group"
}


###

// None admin request for remove user - failed
POST http://localhost:3000/chat/group/remove
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4NzEzZGE0N2Q4OWVmMGQwOWI2YyIsImlhdCI6MTY4MTgxOTQxMX0.c3Ho3Z6qy24FbgEUzNyRkReKliBDzkjsPWhZb_bH8pk
Content-Type: application/json

{
  "groupId": "643e88e1e07d67abe5c1bb47",
  "userId": "643e879914a641e4a41fcbea"
}


###

// admin request for remove user - success
POST http://localhost:3000/chat/group/remove
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgxOTU2OX0.qGtWsKkEDvq5qtV8BMD9qAlnRFjKMv3ffWO5_yRskNY
Content-Type: application/json

{
  "groupId": "643e88e1e07d67abe5c1bb47",
  "userId": "643e879914a641e4a41fcbea"
}


###

// admin request for add user - success
POST http://localhost:3000/chat/group/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgxOTU2OX0.qGtWsKkEDvq5qtV8BMD9qAlnRFjKMv3ffWO5_yRskNY
Content-Type: application/json

{
  "groupId": "643e88e1e07d67abe5c1bb47",
  "userId": "643e879914a641e4a41fcbea"
}


###


POST http://localhost:3000/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4N2IxZTUwYThlNTdjODYzYWY3OCIsImlhdCI6MTY4MTgyMjY3OH0.h1j3hVp9mjMTfjyz7x-k1FFqzpLtigBJaNO-y-T6yHw
Content-Type: application/json

{
  "message": "first message from admin",
  "chatId": "643e887de07d67abe5c1bb3f"
}


###


POST http://localhost:3000/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4Nzk5MTRhNjQxZTRhNDFmY2JlYSIsImlhdCI6MTY4MTgyMjg1Mn0.8dZmLGi7dz4t4q8VU-H7xxjlKw24wYtihqVk-6CafX0
Content-Type: application/json

{
  "message": "to?",
  "chatId": "643e887de07d67abe5c1bb3f"
}


###


Get http://localhost:3000/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2U4Nzk5MTRhNjQxZTRhNDFmY2JlYSIsImlhdCI6MTY4MTgyMjg1Mn0.8dZmLGi7dz4t4q8VU-H7xxjlKw24wYtihqVk-6CafX0
Content-Type: application/json

{
  "chatId": "643e887de07d67abe5c1bb3f",
  "limit": "1"
}


